name: Dependency update

on:
  schedule:
    - cron:  '*/30 * * * *'

jobs:

  build:
    name: Run npm check update and recompile dlls
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - name: install npm-check-updates
        run: npm install -g npm-check-updates
      - name: install dependencies
        run: |
          npm install
          ncu -u
      - name: package dependencies
        run: |
          cd dependencies
          npm install
          ncu -u
          npm run build:dev
          npm run build:prod
      - name: package platform
        run: |
          cd platform
          npm install
          ncu -u
          npm run build
      - uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: |
            +(dependencies|platform)/dll/*.js
            +(dependencies|platform)/dll/*.txt
            +(dependencies|platform)/dll/*.json
          FILES: |
            package.json
      - run: echo '${{ env.GIT_DIFF }}' | jq .
      - name: bump version patch
        if: env.GIT_DIFF
        run: npm version patch
      - name: create PR
        if: env.GIT_DIFF
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
          commit-message: Update dependencies and recompile dlls
          title: Update dependencies
          labels: |
            dependencies
          branch: update-dependencies
