name: Dependency update

on:
  schedule:
    - cron:  '*/30 * * * *'

jobs:

  build:
    name: Run npm check update and recompile dlls
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - name: Install npm-check-updates
        run: npm install -g npm-check-updates
      - name: Update build dependencies
        run: |
          npm install
          ncu -u
          npm install
      - name: Update ctest dependencies
        run: |
          cd ctest
          npm install
          ncu -u
      - name: Package dependencies
        run: |
          cd dependencies
          npm install
          ncu -u
          npm install
          npm run build:dev
          npm run build:prod
      - name: Package platform
        run: |
          cd platform
          npm install
          ncu -u
          npm install
          npm run build:dev
          npm run build:prod
      - name: Package runtime
        run: |
          cd runtime
          npm install
          ncu -u
          npm install
          npm run build:dev
          npm run build:prod
      - name: Check if there are changes
        id: changes
        uses: tj-actions/verify-changed-files@v5.5
        id: changed_files
        with:
          files: |
            package.json
            (dependencies|platform|runtime)/package.json
      - name: Bump version patch
        if: steps.changes.outputs.files_changed == 'true'
        run: npm version patch --no-git-tag-version
      - name: Create PR
        if: steps.changes.outputs.files_changed == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
          commit-message: Update dependencies and recompile dlls
          title: Update dependencies
          labels: |
            dependencies
          branch: update-dependencies
